# Generated by Django 5.2.8 on 2026-03-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
