# Generated by Django 5.2.8 on 2026-03-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
